### PR TITLE
Closes #1, add separate endpoint for uploading files

### LINKED ISSUE #1: Endpoint for uploading files
Right now a single serverless function takes in an array of URLs, downloads the files, uploads them to `api.vercel.com/v2/now/files`, then deploys them with `api.vercel.com/v12/now/deployments`.

This downloading and uploading all the files from this single serverless function hits a Vercel rate limit when the file array is over a certain size.

A better way of doing this would be the `cdn.hackclub.com/api/new` endpoint taking in an array of files, then posting them to a "file upload" serverless function that takes in a file URL and returns a Vercel file URL. That way, each file has it's own size limit, and uploading multiple small files wouldn't total up to a single upload and download number higher than the limit.

### PR DESCRIPTION
**Pull request by KhushrajRathod**
#1

### CODE REVIEW

**Comment by maxwofford** [comment]
Screen Shot 2020-10-30 at 2 19 56 PM

This issue showed up on the deployment build

**Comment by KhushrajRathod** [comment]
Okay that's weird, checking it

**Comment by KhushrajRathod** [comment]
Okay so @maxwofford I've fixed that, also I forgot to add the index prefix for the files, done that

**Comment by maxwofford** [comment]
It built & deployed! Here's the preview: cdn-enbhayqs1.hackclub.dev

When I post a JSON array of fileURLs I get "An error occurred with this application. NO_RESPONSE_FROM_FUNCTION"

**Comment by maxwofford** [comment]
Screen Shot 2020-10-30 at 2 54 47 PM

**Comment by KhushrajRathod** [comment]
Okay do you think it's because of the JSON.parse here (a single URL without an object is passed)?
```
const decoder = new TextDecoder()
const buf = await Deno.readAll(req.body)
const singleFileURL = JSON.parse(decoder.decode(buf))
```

**Comment by maxwofford** [comment]
Yeah, that seems fishy. Maybe that endpoint shouldn't take JSON, but expect a raw string body instead

**Comment by KhushrajRathod** [comment]
Okay I'll change that and let's see

**Comment by KhushrajRathod** [comment]
Broken screenshot link

**Comment by maxwofford** [comment]
Same error. I'll DM you some tokens you can test with locally using `vercel dev`.

**Comment by KhushrajRathod** [comment]
Okay 👍

**Comment by KhushrajRathod** [comment]
@maxwofford Wow, after a long time debugging, it turned out to be just a rogue JSON.parse!
It works locally now for me :)

**Comment by maxwofford** [comment]
Just tested it and it works great locally! Thanks for the improvement 🚀

**Comment by KhushrajRathod** [comment]
:)

**Pull request merged**
